services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - '3307:3306'
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env.dev